steps:
  - label: 'Clean up docker'
    command: 'make cleanup'

  - wait

  - label: 'Test'
    command: 'make test'

  - wait

  - label: 'Build & push image'
    command: 'make build'
    branches: 'master'