steps:
  - label: 'Clean up docker'
    command: 'make cleanup'

  - wait

  - label: 'Test'
    command: 'make test'

  - wait

  - label: 'Package & push image'
    command: 'make package'
    branches: 'master'